[aws]
disabled = true

[directory]
truncate_to_repo = false

[directory.substitutions]
"~/github" = "github.com"

[gcloud]
disabled = true

[git_branch]
symbol = " "

[nodejs]
symbol = " "
format = "using [$symbol$version]($style) "

[ruby]
disabled = true

[package]
format = "[$symbol$version]($style) "
symbol = " "
